# argocd-app-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-{feature_name}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-manifests-repo
    targetRevision: main
    path: environments/feature-{feature_name}
  destination:
    server: https://kubernetes.default.svc
    namespace: feature-{feature_name}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
