apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-feature-branch-name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/asdumitrescu/Weather-App-K8s-Manifest.git
    targetRevision: main
    path: environments/feature-feature-branch-name
  destination:
    server: https://kubernetes.default.svc
    namespace: feature-feature-branch-name
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
