apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${FEATURE_NAME}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-manifests-repo.git  # Replace with your actual repo
    targetRevision: main
    path: '.'  # Root directory
  destination:
    server: https://kubernetes.default.svc
    namespace: ${FEATURE_NAME}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
